name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  DEPLOY_CUSTOMERS: false
  AWS_ACCESS_ID: AKIAYVP4CIPPERUVIFXG
  AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo variables
        run: echo ${{ fromJson(github) }}
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.ref_name }}
          extra_args: --only-verified
      - name: Passing job
        run: exit 0
    outputs:
      deploy_customers: ${{ env.DEPLOY_CUSTOMERS }}
  deploy:
    needs: [prep]
    uses: ./.github/workflows/resuable-workflow.yml
    if: needs.prep.outputs.deploy_customers == 'true'
    strategy:
      matrix:
        account_name:
          - account-1
          - account
    with:
      account_name: ${{ matrix.account_name }}
