name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  ACCOUNTS: ["account-1", "account-2", "account-3"]
jobs:
  arrays:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Run script
        run: echo $ACCOUNTS
        # run: chmod +x ../../bin/test.sh && ../../bin/test.sh
