name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - name: Failing job
      run: exit 0
  build:
    needs: [prep]
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        account_name: false
    if: ${{ matrix.account_name != false }}
    steps:
    - name: Print array
      run: |
        echo "The first value in the array is: ${{ matrix.account_name }}"
