name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env: 
  DEPLOY_CUSTOMERS: false
jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - name: Failing job
      run: exit 0
    outputs:
      deploy_customers: ${{ env.DEPLOY_CUSTOMERS }}
  build:
    needs: [prep]
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        account_name:
          - account-1
    if: jobs.prep.outputs.deploy_customers == 'true'
    steps:
    - name: Print array
      run: |
        echo "The first value in the array is: ${{ matrix.account_name }}"
